language: objective-c
#before_install:
# - brew update
install:

  # http://stackoverflow.com/questions/23796448/homebrew-error-occured-when-i-command-brew-cask-install-virtualbox-or-brew-ca
  # - brew uninstall brew-cask
  - brew tap caskroom/cask
  - brew install brew-cask
  - brew cask install virtualbox

  # - mkdir -p $(brew --repo)/Library/Taps
  # - ln -s $PWD $(brew --repo)/Library/Taps/azukiapp-azk
  # - brew tap --repair
# script:
  #- brew audit azk
  #- brew install -v azk
matrix:
  fast_finish: true
