language: objective-c

install:

  # http://stackoverflow.com/questions/23796448/homebrew-error-occured-when-i-command-brew-cask-install-virtualbox-or-brew-ca
  - brew tap caskroom/cask
  - brew install brew-cask
  - brew cask install virtualbox

  # install azk
  - brew install azukiapp/azk/azk

  # create dns resolver
  - sudo mkdir -p /etc/resolver
  - sudo touch /etc/resolver/azk.dev
  - echo "nameserver 192.168.50.4.53" | sudo tee -a /etc/resolver/azk.dev

script:
  # setting default path as azk
  - export PATH=`pwd`/bin:$PATH
  - rm -Rf node_modules lib/azk lib/nvm lib/spec
  - make
  - azk nvm grunt vm-download
  - azk agent start
  - azk nvm grunt slow_test
  - make package_mac

matrix:
  fast_finish: true
